---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: websvcport
      targetPort: webport
      port: 80